# Generated by Django 4.1 on 2024-12-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catalogoDocumetosMarinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDocumento', models.IntegerField()),
                ('nombreDocumento', models.CharField(max_length=60, verbose_name='Nombre del Documento')),
                ('codigoGeneralDocumento', models.CharField(max_length=50, verbose_name='Código o Nobre Internacional del Documento')),
            ],
        ),
        migrations.CreateModel(
            name='certificadoMarino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.IntegerField()),
                ('cedulaMarino', models.CharField(max_length=12, verbose_name='Cedula Marino')),
                ('idDocumento', models.IntegerField(verbose_name='Tipo de Documento')),
                ('fechaExpedicion', models.DateField(verbose_name='Fecha de Expedición Documento')),
                ('fechavencimiento', models.DateField(verbose_name='Fecha de vencimiento Documento')),
                ('fechaControl', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Marinos',
            fields=[
                ('cedula', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Cedula')),
                ('nombres', models.CharField(max_length=40, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=40, verbose_name='Apellidos')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('fechaControl', models.DateField(verbose_name='Fecha de Nacimiento')),
            ],
        ),
    ]
